### ISSUE TITLE
init truncation / corruption

### ISSUE THREAD

**Issue by sbuller** [owenson/tiny-linux-bootloader#3]
I'm running into an issue now where it seems the init file is truncated and possibly corrupted. The init file and kernel work correctly when used with with qemu's '-initrd' and '-kernel', but all my files after a certain point are missing, and the last seems to be corrupt. I tried to put busybox on my init file so that I could better see exactly what I was left with, but it turns out busybox is still bigger than my 'big' init file.

The version prior to the last commit seems to exhibit the exact same behaviour, cutting off the init file at exactly the same point. I've collected the following data:

* 362 bytes: works
* 180K: files from after 60-70 sectors (30-35K) into the cpio are missing from the filesystem after boot
* 590K: busybox crashes
* 180K + 2M zeroes: same as 180K
* 180K + 3M zeroes: kernel crashes
* 180K + 23M zeroes: kernel crashes (still works with qemu's -initrd and -kernel)

**Comment by owenson** [comment]
Hi

Ok are you able to send me the kernel and init?

Thanks

**Comment by sbuller** [comment]
Of course, sorry I didn't include them straight off.

http://filebin.ca/2s8HZXwPEnXC/big.init
http://filebin.ca/2s8I48ygr9WG/barebones

**Comment by owenson** [comment]
Hi - just to let you know I'm still looking it this.  An initial debug hasn't revealed anything abnormal but will keep trying.

**Comment by owenson** [comment]
I've checked in a fix and your init now works with my qemu using the command line

qemu-system-x86_64 -hda disk

The downside is I've no idea why the fix works.  Previously the kernel was loaded and then the initrd immediately following it.  I've now moved the initrd to a fixed offset of 127mb in ram which is where qemu puts it and it's now working.  But it wont accept many other valid offsets that I try.

The downside to the fix is the computer must have ~150mb of system memory now.

**Comment by sbuller** [comment]
Thank you.

**Comment by sbuller** [comment]
http://wiki.osdev.org/Memory_Map_(x86)

I notice in there near the bottom of the page, it mentions an ISA memory hole that could be related. Anyhow, using the value qemu uses makes a lot of sense to me.

**Comment by owenson** [comment]
Thanks for the link.  It was being mapped at 0xDB6600 to 0xDE6000, so it looks like it misses the ISA hole.  Strangely if I mapped it at 32 or 64mb it also didnt work - and they should be clear.
